controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - left_finger_joint
      - right_finger_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false

    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.05

      base_joint:
        trajectory: 0.2
        goal: 0.1
      shoulder_joint:
        trajectory: 0.2
        goal: 0.1
      elbow_joint:
        trajectory: 0.2
        goal: 0.1
      wrist_joint:
        trajectory: 0.2
        goal: 0.1
      left_finger_joint:
        trajectory: 0.2
        goal: 0.1
      right_finger_joint:
        trajectory: 0.2
        goal: 0.1